version: "3.8"
services:
  api:
    container_name: poc_credits
    restart: always
    build:
     context: ./
     dockerfile: Dockerfile
    ports:
      - "4500:4500"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./db/mongo:/data/db 
    ports:
      - "27017:27017"